### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by uroboro** [uroboro/mach_portal#1]
- [ ] Delay alert popup until exploit is done.
- [ ] Reroute all syslog/printf caused by jailbreak to go to nc-client's textview.
- [ ] Detect if device is already jailbroken and connect without re-exploiting.
